name: check-chrome-version

on:
  workflow_dispatch:

jobs:
  check-chrome-version:
    runs-on: ubuntu-24.04
    steps:
      - name: Print Chrome and ChromeDriver version (before)
        run: |
          echo "== Before =="
          echo "Chrome version:"
          google-chrome --version || chromium-browser --version || echo "Chrome not found"
          echo "ChromeDriver version:"
          chromedriver --version || echo "ChromeDriver not found"

      - name: Downgrade to Chrome & ChromeDriver 125
        run: |
          set -ex

          echo "Removing existing Chrome and ChromeDriver"
          sudo apt-get remove -y google-chrome-stable || true
          sudo rm -f /usr/bin/google-chrome /usr/bin/chromedriver

          echo "Installing Chrome 125"
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/125.0.6422.60/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome125
          sudo ln -sf /opt/chrome125/chrome /usr/bin/google-chrome

          echo "Installing ChromeDriver 125"
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/125.0.6422.60/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Print Chrome and ChromeDriver version (after)
        run: |
          echo "== After =="
          echo "Chrome version:"
          google-chrome --version
          echo "ChromeDriver version:"
          chromedriver --version