name: test-conda-env

on:
  workflow_dispatch:

jobs:
  setup-conda:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup conda environment with python 3.9 and R
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: python_3_with_R_and_tensorflow
          environment-file: testing/env_python_3_with_R_and_tensorflow.yml
          python-version: 3.9
          channels: conda-forge,defaults
          channel-priority: true
          auto-activate-base: false
          use-mamba: true

      - name: Verify environment is activated
        run: |
          which python
          python --version
          conda info --envs